// samples/frameworks/angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MRZScanner, MRZDataLabel } from 'dynamsoft-mrz-scanner';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  result: {
    image: string;
    data: string;
  } = {
    image: '',
    data: '',
  };

  ngOnInit(): void {
    // Configuration object for initializing the MRZ Scanner instance
    const config = {
      license: 'DLS2eyJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSJ9', // Replace with your Dynamsoft license key
    };

    const mrzscanner = new MRZScanner(config);

    mrzscanner.launch().then((_result) => {
      const { originalImageResult, data } = _result;
      const canvas = originalImageResult?.toCanvas();
      const dataUrl = canvas.toDataURL('image/png');

      const formattedMRZ = Object.entries(data)
        .map(([key, value]) => {
          return `${MRZDataLabel[key]}:\n${
            key === 'mrzText' ? value : JSON.stringify(value)
          }`;
        })
        .join('\n\n');

      this.result = { image: dataUrl, data: formattedMRZ };
    });
  }
}

<div class="mrz-scanner-hello-world-page">
  <div class="mrz-scanner-title">
    <h2 class="mrz-scanner-title-text">Hello World for Angular</h2>
    <img class="mrz-scanner-title-logo" src="./favicon.ico" alt="logo" />
  </div>
  <div class="mrz-scanner-result-container">
    <img
      *ngIf="result?.image"
      class="result-img"
      [src]="result.image"
      alt="mrz-result"
    />
    <div *ngIf="result?.data" class="result-data">{{ result.data }}</div>
  </div>
</div>

// samples/frameworks/react-hooks/src/App.js
import { useEffect, useState } from "react";
import { MRZScanner, MRZDataLabel } from "dynamsoft-mrz-scanner";
import reactLogo from "./logo.svg";
import "./App.css";

function App() {
  const [result, setResult] = useState({
    image: "",
    data: "",
  });
  useEffect(() => {
    // Configuration object for initializing the MRZ Scanner instance
    const config = {
      license: "DLS2eyJvcmdhbml6YXRpb25JRCI6IjIwMDAwMSJ9", // Replace with your Dynamsoft license key
    };

    // Create an instance of the mrzScanner with the provided configuration
    const mrzscanner = new MRZScanner(config);

    // Launch the scanner; once a mrz is detected and save the result
    mrzscanner.launch().then((_result) => {
      const { originalImageResult, data } = _result;

      // Get captured MRZ image
      const canvas = originalImageResult?.toCanvas();
      const dataUrl = canvas.toDataURL("image/png");

      // Format data as a string

      const formattedMRZ = Object.entries(data)
        .map(([key, value]) => {
          return `${MRZDataLabel[key]}:\n${key === "mrzText" ? value : JSON.stringify(value)}`;
        })
        .join("\n\n");

      setResult({ image: dataUrl, data: formattedMRZ });
    });
  }, []);
  return (
    <div className="mrz-scanner-hello-world-page">
      <div className="mrz-scanner-title">
        <h2 className="mrz-scanner-title-text">Hello World for React</h2>
        <img className="mrz-scanner-title-logo" src={reactLogo} alt="logo"></img>
      </div>
      <div className="mrz-scanner-result-container">
        {result?.image && <img className="result-img" src={result.image} alt="mrz-result" />}
        {result?.data && <div className="result-data">{result.data}</div>}
      </div>
    </div>
  );
}

export default App;
